---
apiVersion: v1
kind: Service
metadata:
  name: servitium
  labels:
    app.kubernetes.io/name: servitium
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  externalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/name: servitium
  ports:
    - name: http
      nodePort: null
      port: 8099
      protocol: TCP
      targetPort: http
