---
apiVersion: v1
kind: Service
metadata:
  name: servitium
  labels:
    app.kubernetes.io/name: servitium
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: servitium
  ports:
    - name: http
      port: 8099
      nodePort: 30099
      protocol: TCP
      targetPort: http
