---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servitium
  labels:
    app.kubernetes.io/name: servitium
    app.kubernetes.io/instance: live
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: servitium
      app.kubernetes.io/instance: live
  template:
    metadata:
      labels:
        app.kubernetes.io/name: servitium
        app.kubernetes.io/instance: live
    spec:
      containers:
        - name: servitium
          env:
            - name: MYSQL_DATABASE
              value: servitium
            - name: MYSQL_USER
              value: servitium
          ports:
            - name: http
              containerPort: 8099
              protocol: TCP
          volumeMounts:
            - name: servitium-secrets
              mountPath: /run/secrets/servitium
              readOnly: true
      volumes:
        - name: servitium-secrets
          secret:
            secretName: servitium-secrets
            defaultMode: 256
            items:
              - key: bot-token
                path: discord-bot-token
              - key: password
                path: mysql-password
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-wireguard-http
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: servitium
      app.kubernetes.io/instance: live
  ingress:
    - from:
        - ipBlock:
            cidr: 192.168.21.0/24
        - ipBlock:
            cidr: 192.168.1.0/24
      ports:
        - port: 8099
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: servitium
      app.kubernetes.io/instance: live
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-mysql-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: servitium
      app.kubernetes.io/instance: live
