---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servitium
nameSuffix: ""
resources:
  - ../../base
images:
  - name: ghcr.io/hannosirkel/servitium
    newName: ghcr.io/hannosirkel/servitium
    digest: sha256:e2bfd2ce645f4bba0d0cd60482b6bf41ef6d2af4699223b00624ed331ceb6cdb
patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
