---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servitium
nameSuffix: ""
resources:
  - ../../base
images:
  - name: ghcr.io/hannosirkel/servitium
    newName: ghcr.io/hannosirkel/servitium
    digest: sha256:c502c41083483d8372591d5e319794f0221e295446144d24015d3c2a640a41e1
patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
